{% set name = "charset-normalizer" %}
{% set version = "3.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/charset-normalizer-{{ version }}.tar.gz
  sha256: d9137a876020661972ca6eec0766d81aef8a5627df628b664b234b73396e727e

build:
  number: 0
  noarch: python
  entry_points:
    - normalizer = charset_normalizer.cli:cli_detect
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - charset_normalizer
  commands:
    - pip check
    - normalizer --help
  requires:
    - pip

about:
  home: https://github.com/Ousret/charset_normalizer
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  license: MIT
  license_file:
    - LICENSE
    - data/NOTICE.md

extra:
  recipe-maintainers:
    - ocefpaf
