{% set name = "charset-normalizer" %}
{% set version = "3.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6fce4b8500244f6fcb71465d4a4930d132ba9ab8e71a7859e6a5d59851068d14

build:
  number: 0
  noarch: python
  entry_points:
    - normalizer = charset_normalizer.cli:cli_detect
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - charset_normalizer
  commands:
    - pip check
    - normalizer --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Ousret/charset_normalizer
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  license: MIT
  license_file:
    - LICENSE
    - data/NOTICE.md

extra:
  recipe-maintainers:
    - ocefpaf
