{% set name = "charset-normalizer" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 223217c3d4f82c3ac5e29032b3f1c2eb0fb591b72161f86d93f5719079dae93e

build:
  number: 0
  noarch: python
  entry_points:
    - normalizer = charset_normalizer.cli:cli_detect
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - charset_normalizer
  commands:
    - pip check
    - normalizer --help
  requires:
    - pip

about:
  home: https://github.com/Ousret/charset_normalizer
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  license: MIT
  license_file:
    - LICENSE
    - data/NOTICE.md

extra:
  recipe-maintainers:
    - ocefpaf
